name: docker push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    # Login to Docker Hub
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #docker hub username
          password: ${{ secrets.DOCKER_PASSWORD }} #docker hub access token 

    # Checkout the repo to use the file present in repo  
      - name: checkout
        uses: actions/checkout@v4

    # Push the  built image to the docker hub registry
      - name: push
        uses: docker/build-push-action@v2
        with:
          context: . #if the file is in the root directory of the repository
          #file: ./docker/Dockerfile #if file is present in different directory, mention absolute path here
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/httpd:${{ github.run_number }} #github.run_number --> this provide run number as tag to image

#### Manual build and Push Image
      #- name: Build and Push Image
      #  run: |
        #  docker build . -t ${{ secrets.DOCKER_USERNAME }}/httpd:${{ github.run_number }} 
        #  docker push ${{ secrets.DOCKER_USERNAME }}/httpd:${{ github.run_number }}

  container:
    runs-on: self-hosted
    needs: docker
    steps:
      - name: build container
        run: | 
          sudo yum remove docker* podman* -y
          sudo dnf -y install dnf-plugins-core
          sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
          sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
          sudo systemctl start docker
          docker run -itd -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/httpd:${{ github.run_number }}