name: docker push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: checkout
        uses: actions/checkout@v4

      #- name: Build and push
      #  run: docker build . -t ramesh0112/httpd:${{ github.run_number }}

      - name: push
      #  run: docker push ramesh0112/httpd:${{ github.run_number }}
        uses: docker/build-push-action@v2
        with:
          context: .
          #file: ./.github/workflows/Dockerfile
          push: true
          tags: ramesh0112/httpd:new, ramesh0112/httpd:${{ github.run_number }}