name: docker push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo $DO_USER
          echo $DO_PASS

        env: 
          #DO_USER: ${{ vars.DOCKERHUB_USERNAME }}
          DO_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
          DO_USER: DOCKERHUB_USERNAME
          #DO_PASS: secrets.DOCKERHUB_TOKEN