name: docker push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo ${{ vars.DOCKERHUB_USERNAME }}
          echo ${{ secrets.DOCKERHUB_TOKEN }}